web/urls.py
# Copyright (c) NASK, NCSC
# 
# This file is part of HoneySpider Network 2.0.
# 
# This is a free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
#from django.conf.urls import patterns, include, url #Django 1.4
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.contrib.sites.models import Site
from django.contrib.auth.models import Group

from web.app.feeds import AllUrls, NonBenignUrls

static_admin = os.path.join(os.path.dirname(__file__), 'app/static_admin')

admin.autodiscover()

urlpatterns = patterns('web.app.views',

    (r'^$', 'jobs_overview'),
    (r'^jobs/$', 'jobs_overview'),

    (r'^job/(?P<job_id>\d+)/$', 'job_details'),

    (r'^job/(?P<job_id>\d+)/analysis/(?P<node>\d+:\d+)/$', 'analysis_overview'),
    (r'^job/(?P<job_id>\d+)/analysis/(?P<node>\d+:\d+)/byanalyzer/(?P<analyzer>[\w-]+)/$', 'analysis_by_analyzer'),
    (r'^job/(?P<job_id>\d+)/analysis/(?P<node>\d+:\d+)/byurl/(?P<subnode>\d+:\d+)/$', 'analysis_by_url'),

    (r'^getattachment/(?P<node>\d+:\d+:?\w*)/(?P<filename>\d+:\d+:\d+)/$', 'get_attachment'),

    (r'^schedule/$', 'schedule_overview'),
    (r'^schedule/(?P<job_id>\d+)/$', 'schedule_details'),
    (r'^schedule/edit/(?P<job_id>\d+)/$', 'schedule_details_edit'),

    (r'^newjob/$', 'new_job'),
    (r'^newjobdone/(?P<job_id>\d+)/$', 'new_job_done'),

    (r'^nopermission/$', 'no_permission'),
    (r'^about/$', 'about_page'),
    (r'^logout/$', 'logout_page'),
    (r'^switchuser/$', 'switch_user'),

    (r'^statistics/$', 'statistics_page'),

    # AJAX REQUESTS
    (r'^getanalyzerdetails/$', 'get_analyzer_details'),
    (r'^schedule/disable/$', 'disable_schedule'),
    (r'^schedule/delete/$', 'delete_schedule'),
    (r'^getworkflowdetails/$', 'get_workflow_details')

)

#TODO: login with REMOTE_USER for SSO
urlpatterns += patterns('',
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^static_admin/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': static_admin }),
    (r'^password/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'} ),
    (r'^password_done/$', 'django.contrib.auth.views.password_change_done' ),

    (r'^feeds/(?P<job_id>\d+)/all/$', AllUrls() ),
    (r'^feeds/(?P<job_id>\d+)/nonbenign/$', NonBenignUrls() ),

    (r'^admin/', include(admin.site.urls)),
)

web/app/models.py
# Copyright (c) NASK, NCSC
# 
# This file is part of HoneySpider Network 2.0.
# 
# This is a free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.contrib.auth.models import User

CLASSIFICATIONS = {
    'UNKNOWN': 1,
    'UNCLASSIFIED': 1,
    'BENIGN': 2,
    'OBFUSCATED': 3,
    'SUSPICIOUS': 3,
    'MALICIOUS': 4,
}


class Workflow (models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250)
    description = models.TextField(null=True)
    enabled = models.BooleanField(default=True)
    uses_file_upload = models.BooleanField(default=False)
    revision = models.TextField()
    date = models.DateTimeField(null=True)
    xml = models.TextField()

    def __unicode__(self):
        return '%s %s %s' % (self.id, self.name, self.date )


class Schedule (models.Model):

    NEW_STATUS = 1
    UPDATE_STATUS = 2
    ACTIVE_STATUS = 3
    DEACTIVATE_STATUS = 4
    DELETED_STATUS = 5
    DELETE_STATUS = 6
    DEACTIVATED_STATUS = 7
    
    SCHEDULE_STATUS = (
                            (NEW_STATUS, 'Adding'),
                            (UPDATE_STATUS, 'Updating'),
                            (ACTIVE_STATUS, 'Active'),
                            (DEACTIVATE_STATUS, 'Deactivating'),
                            (DEACTIVATED_STATUS, 'Deactivated'),
                            (DELETED_STATUS, 'Deleted'),
                            (DELETE_STATUS, 'Deleting')
                       )

    id = models.AutoField(primary_key=True)
    created_by = models.ForeignKey(User)
    job_name = models.CharField(max_length=250)
    scheduled_start = models.DateTimeField(null=True)
    workflow = models.ForeignKey(Workflow, null=True, related_name='schedule')
    is_public = models.BooleanField(default=False)
    status = models.IntegerField(choices=SCHEDULE_STATUS)
    cron_expression = models.CharField(max_length=150, null=True)

    def __unicode__(self):
        return self.job_name


class ServiceParameter (models.Model):
    id = models.AutoField(primary_key=True)
    service = models.CharField(max_length=250)
    param_key = models.CharField(max_length=250)
    param_value = models.CharField(max_length=250)
    schedule = models.ForeignKey(Schedule, related_name='parameters')

    def clean(self):
        self.service = self.service.strip()
        self.param_key = self.param_key.strip()
        self.param_value = self.param_value.strip()

    def __unicode__(self):
        return '%s.%s=%s' % ( self.service, self.param_key, self.param_value )

class Job (models.Model):
    
    ACCEPTED_STATUS = 1 
    STARTING_STATUS = 2
    PROCESSING_STATUS = 3
    COMPLETED_STATUS = 4
    FAILING_STATUS = 5
    FAILED_STATUS = 6
    CANCELLING_STATUS = 7
    CANCELLED_STATUS = 8
  
    JOBSTATUS = (
                    (ACCEPTED_STATUS, 'ACCEPTED'),
                    (STARTING_STATUS, 'STARTING'),
                    (PROCESSING_STATUS, 'PROCESSING'),
                    (COMPLETED_STATUS, 'COMPLETED'),
                    (FAILING_STATUS, 'FAILING'),
                    (FAILED_STATUS, 'FAILED'),
                    (CANCELLING_STATUS, 'CANCELLING'),
                    (CANCELLED_STATUS, 'CANCELLED')
                 )

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250)
    started = models.DateTimeField(null=True)
    finished = models.DateTimeField(null=True)
    owner = models.ForeignKey(User, null=True)
    workflow = models.ForeignKey(Workflow, null=True)
    is_public = models.BooleanField()
    schedule = models.ForeignKey(Schedule, null=True)
    frameworkid = models.IntegerField(unique=True, null=True)
    status = models.IntegerField(choices=JOBSTATUS, default=PROCESSING_STATUS)

    def __unicode__(self):
        return self.name

web/app/forms.py
# Copyright (c) NASK, NCSC
# 
# This file is part of HoneySpider Network 2.0.
# 
# This is a free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re

from django import forms
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.forms.extras.widgets import SelectDateWidget
from django.conf import settings
from croniter import croniter
from datetime import datetime

from web.app.models import Schedule, Workflow
from web.app.custom.form import CustomRadioFieldRenderer

ISPUBLIC_CHOICES = ((1, 'Yes'), (0, 'No'))
SCHEDULEWHEN_CHOICES = (('once', 'Once, at given date and time'), ('cron', 'Schedule with cron-like expression'))


class JobForm (forms.Form):

    schedule_when = forms.ChoiceField(
                                      choices=SCHEDULEWHEN_CHOICES,
                                      widget=forms.RadioSelect(renderer=CustomRadioFieldRenderer),
                                      initial='once'
                                    )

    schedule_date = forms.DateField( required=False, widget=SelectDateWidget() )
    schedule_time = forms.TimeField(
                                     required=False,
                                     input_formats=['%H:%M'],
                                     widget=forms.TimeInput( format='%H:%M', attrs={'placeholder': 'HH:MM', 'class': 'width_narrow'} )
                                    )

    cron_expression = forms.CharField( required=False, widget=forms.TextInput( attrs={'class': 'minwidth_200'} ) )
    
    job_name = forms.CharField( widget=forms.TextInput( attrs={'class': 'minwidth_200'} ) )

    is_public = forms.ChoiceField(
                                    choices=ISPUBLIC_CHOICES,
                                    widget=forms.RadioSelect(renderer=CustomRadioFieldRenderer),
                                    initial='1'
                                 )

    edit_processed_jobs = forms.CharField( required=False, widget=forms.HiddenInput())
    is_public_org = forms.CharField( required=False, widget=forms.HiddenInput())

    latestWorkflowsSQL = 'SELECT * FROM app_workflow WHERE name IN (SELECT name FROM app_workflow GROUP BY name HAVING date = MAX(date)) AND enabled = true order by name'

    workflow = forms.ChoiceField( 
                                  choices=[(wf.id,wf.name) for wf in Workflow.objects.raw(latestWorkflowsSQL)],
                                  widget=forms.Select( attrs={'class': 'minwidth_200'} )
                                )

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)

        workflowId = args[0].get('workflow') if args else None

        selectedWorkflow = None
        if workflowId:
            try:
                selectedWorkflow = Workflow.objects.get(id=workflowId)
            except:
                pass
        else:
            try:
                selectedWorkflow = Workflow.objects.raw(self.latestWorkflowsSQL)[0:1]
            except ObjectDoesNotExist:
                pass
            else:
                if selectedWorkflow:
                    selectedWorkflow = selectedWorkflow[0]

        if selectedWorkflow:
            self.fields['workflow_description'] = forms.CharField(initial=selectedWorkflow.description, required=False)
            self.fields['workflow_xml'] = forms.CharField(initial=selectedWorkflow.xml, required=False )

            hasFeederFile = True if args and args[0].get('feeder_file') else False
            inputFieldClass = 'hide' if not selectedWorkflow.uses_file_upload or hasFeederFile else ''
            self.fields['feeder_file'] = forms.FileField(
                                                           required=False,
                                                           widget=forms.ClearableFileInput(attrs={'class':inputFieldClass})
                                                         )

    def clean(self):

            scheduleWhen = self.cleaned_data.get('schedule_when', None)
            scheduleDate = self.cleaned_data.get('schedule_date', None)
            scheduleTime = self.cleaned_data.get('schedule_time', None)
            cronExpression = self.cleaned_data.get('cron_expression', None)
            jobName = self.cleaned_data.get('job_name', None)
            
            workflowId = self.cleaned_data.get('workflow', None)

            if scheduleWhen == 'once':
                if scheduleDate == None and self._errors.get('schedule_date', None) == None:
                    self._errors['schedule_date'] = self.error_class(['A valid date is required.'])
 
                if scheduleTime == None and self._errors.get('schedule_time', None) == None:
                    self._errors['schedule_time'] = self.error_class(['A valid time is required.'])

                try:
                    if datetime( scheduleDate.year, scheduleDate.month, scheduleDate.day, scheduleTime.hour, scheduleTime.minute ) <= datetime.now():
                        self._errors['schedule_date'] = self.error_class(['Cannot schedule jobs to run in the past.'])
                        self._errors['schedule_time'] = self.error_class(['Cannot schedule jobs to run in the past.'])
                except:
                    pass
            
            if scheduleWhen == 'cron':
                if cronExpression == None:
                    self._errors['cron_expression'] = self.error_class(['A valid cron expression is required.'])
                else:
                    
                    cronExpression = re.sub('\s+', ' ', cronExpression)
                    
                    dtBase = datetime.now()
                    try:
                        cronSchedule = croniter( cronExpression, dtBase )
                    except Exception as e:
                        self._errors['cron_expression'] = self.error_class(['Cron expression not accepted.'])
                    else:
                        split_re = re.compile("\s+")
                        cronList = split_re.split( cronExpression )                        
                        if len( cronList ) is not 5:
                            self._errors['cron_expression'] = self.error_class(['Cron expression only accepts 5 columns'])
                        elif re.match( '[a-zA-Z]', cronList[3]):
                            print 'Invalid month expression'
            
            if Schedule.objects.filter(job_name=jobName).exclude(status=Schedule.DELETED_STATUS).count() > 1:
                self._errors['job_name'] = self.error_class(['A job schedule with this name already exists'])
            
            try:
                self.cleaned_data['workflow'] = Workflow.objects.get(id=workflowId)
            except ObjectDoesNotExist:
                self._errors['workflow'] = self.error_class(['Not a valid workflow, please select one from the available workflows.'])

            # check if every field of an added parameter is not blank
            parameterGroups = {}
            for inputFieldName, value in self.cleaned_data.iteritems():

                if inputFieldName.startswith('workflow_parameter'):
                    groupNumber = re.sub(r'.*?_(\d+)$', r'\1', inputFieldName)
                    if groupNumber in parameterGroups:
                        parameterGroups[groupNumber][inputFieldName] = value.strip()
                    else:
                        parameterGroups[groupNumber] = {inputFieldName: value.strip()}

            for groupNumber, parameterGroup in parameterGroups.iteritems():
                if (
                        not parameterGroup['workflow_parameter_service_%s' % groupNumber] \
                        or not parameterGroup['workflow_parameter_name_%s' % groupNumber] \
                        or not parameterGroup['workflow_parameter_value_%s' % groupNumber]
                    ) \
                    and not \
                    (
                        not parameterGroup['workflow_parameter_service_%s' % groupNumber] \
                        and not parameterGroup['workflow_parameter_name_%s' % groupNumber] \
                        and not parameterGroup['workflow_parameter_value_%s' % groupNumber]
                    ):

                    self._errors['workflow_parameter_service_%s' % groupNumber] = self.error_class(["Please specify 'service', 'name' and 'value'."])

            return self.cleaned_data


class JobSearchForm (forms.Form):
    job_search = forms.CharField( widget=forms.TextInput( attrs={'class': 'minwidth_200'}))
    

web/templates/analysis_by_analyzer.html
{% extends "analysis_details.html" %}

{% block tableTitleSetting %}
<div class="title"><span class="bold">{{ currentPage }}</span> analysis</div>
{% endblock %}

{% block tableHeaderSetting %} URL {% endblock %}

{% block helpInfo %} Select a URL from the list above to display detailed analysis information. {% endblock %}

web/templates/analysis_by_url.html
{% extends "analysis_details.html" %}

{% block tableTitleSetting %}
{% with "Analysis for "|add:currentPage as tableTitle %}
<div class="title"> {{ tableTitle|urlizetrunc:65 }}</div>
{% endwith %}
{% endblock %}
{% block tableHeaderSetting %} Analyzer {% endblock %}

{% block helpInfo %} Select an analyzer from the list above to display detailed analysis information. {% endblock %}

web/templates/analyzer_data.html
{% if list_no_value %}
<span class="dataListTitleEmpty">{{ name }} <span class="italic">(empty list)</span></span><ul>
{% endif %}
{% if list_w_value %}
<span class="dataListTitle pointer"><span class="listFolding">+</span> {{ name }} </span><ul>
{% endif %}
{% if text_gt_130 %}
<span class="dataKeyText">{{ name }}</span><pre class="pointer dataValueTextPretty">{{ value }}</pre>
{% endif %}
{% if text_lt_130 %}
<span class="dataKeyText">{{ name }}</span><span class="dataValueText">{{ value }}</span>
{% endif %}
{% if boolean %}
<span class="dataKeyBoolean">{{ name }}</span><span class="dataValue{{ value }}">&nbsp;</span>
{% endif %}
{% if integer %}
<span class="dataKeyInteger">{{ name }}</span><span class="dataValueInteger">{{ value }}</span>
{% endif %}
{% if time %}
<span class="dataKeyTime">{{ name }}</span><span class="dataValueTime">{{ value }}</span>
{% endif %}
{% if attachment_w_node %}
<span class="dataKeyAttachment">{{ name }}</span><a href="/getattachment/{{ node }}/{{ value }}/" class="dataValueAttachment">{{ value }}</a>
{% endif %}
{% if attachment_no_node %}
<span class="dataKeyAttachment">{{ name }}</span><span class="dataValueAttachment">{{ value }} (could not make link)</span>
{% endif %}

web/templates/job_form.html
{% if message %}

<div>{{ message }}</div>

{% else %}
<div>
    <form enctype="multipart/form-data" method="post" action="." id="form_job">{% csrf_token %}
       <fieldset>
            <legend>Workflow</legend>
            <div>
                <label for="id_workflow" class="label">Select a workflow: *</label>
                {{ jobForm.workflow }}
                {{ jobForm.workflow.errors }}
            </div>
			<div>
				<span class="label align_top">Workflow description:</span>
				<pre class="label" id="workflow_description">{{ jobForm.workflow_description.value }}</pre>
				<input type="hidden" name="workflow_description" id="hid_workflow_description" value="{{ jobForm.workflow_description.value }}">
			</div>
			
			{% if feederFileIsUsed %}
			<div id="feeder_file_is_uploaded">
				<span class="label align_top">Feeder file:</span> 
		        <span id="span_feeder_file_is_uploaded" class="label">A file has been submitted for this workflow.<br><span class="span_link pointer" id="replace_feeder_file">Replace or delete uploaded file</span></span>
		        <input type="hidden" name="feederFileIsUsed" id="id_feederFileIsUsed" value="{{ feederFileIsUsed }}">
 			</div>
			{% endif %}
			 
			<div class="hide align_top" id="feeder_file_upload">
		        <label for="id_feeder_file" class="label" id="label_feeder_file">Feeder file:</label>
				{{ jobForm.feeder_file }}
				{{ jobForm.feeder_file.errors }}
	        </div>

            <div>
                <label for="workflow_parameter" class="label align_top">Workflow parameters:<br>(optional)</label>
                <div class="label align_top">
                	<span class="inline width_default">Service</span>
                	<span class="inline width_default">Parameter name</span>
                	<span class="inline width_default">Parameter value</span>


                	{% if jobForm.workflow_parameter_service_1 %}
	                	{% for parameterGroupNumber in parameterGroupNumbers %}

				    <div class="parameters_div" data-parameterscount="{{ parameterGroupNumber }}">	                	
	                		{% for parameterPrefix in parameterPrefixes %}

		                		{% for field in jobForm %}

				                	{% if field.html_name == parameterPrefix|add:parameterGroupNumber %}
				                		{% if field.errors %}
						                	{{ field.errors }}<br><br>
						                {% endif %}

			            	    		{{ field }}
					    
				                	{% endif %}
		    	            	{% endfor %}
		    	            {% endfor %}
		    	    	<img src="/static_admin/img/admin/icon_deletelink.gif" class="pointer btn_remove_parameter {% if parameterGroupNumber == '1' %}hide{% endif %}">
            		</div>
						{% endfor %}

                	{% else %}
	                <div class="parameters_div" data-parameterscount="1">
		                <input type="text" id="id_workflow_parameter_service_1" name="workflow_parameter_service_1" class="minwidth_200 workflow_parameter_service" placeholder="Service">
		                <input type="text" id="id_workflow_parameter_name_1" name="workflow_parameter_name_1" class="minwidth_200 workflow_parameter_name" placeholder="Parameter name">
		                <input type="text" id="id_workflow_parameter_value_1" name="workflow_parameter_value_1" class="minwidth_200 workflow_parameter_value" placeholder="Parameter value">
		                <img src="/static_admin/img/admin/icon_deletelink.gif" class="pointer btn_remove_parameter hide">
	               	</div>
	               	{% endif %}
	               	
	               	<span class="span_link inline pointer" id="add_parameter">Add parameter</span>
               	</div>
            </div>

			<div>
				<span class="label align_top span_link pointer" id="toggle_workflow_xml">Show/Hide workflow XML</span>
				<pre class="hide" id="workflow_xml">{{ jobForm.workflow_xml.value }}</pre>
				<input type="hidden" name="workflow_xml" id="hid_workflow_xml" value="{{ jobForm.workflow_xml.value }}">
			</div>
            
       </fieldset>
    
       <fieldset>
            <legend>Scheduling</legend>
            <div>
                <span class="label">When to run the job? *</span>           
               {{ jobForm.schedule_when }}
               {{ jobForm.schedule_when.errors }}
            </div>
                      
            <div id="div_scheduling_options_once" style="display:None">
            	<span id="span_scheduling_options_once" class="italic">Date and time options</span>
                <div class="schedule_once_options">
                    <label for="id_schedule_once_date" class="label">Start date:</label>
                    {{ jobForm.schedule_date }}
                    {{ jobForm.schedule_date.errors }}
                </div>
                <div class="schedule_once_options">
                    <label for="id_schedule_time" class="label">Start time:</label>
                    {{ jobForm.schedule_time }}
                    {{ jobForm.schedule_time.errors }}
                </div>
            </div>

            <div id="div_scheduling_options_cron" style="display:None">
            	<span id="span_scheduling_options_cron" class="italic">Cron-like scheduling</span>
                <div class="schedule_cron_options">
                    <label for="id_schedule_cron_expression" class="label">Cron expression:</label>
                    {{ jobForm.cron_expression }}
                    {{ jobForm.cron_expression.errors }}
                </div><br>
                <span class="label">&nbsp;</span>
            <pre class="inline monospacefont">
 *    *    *    *    *
 ┬    ┬    ┬    ┬    ┬
 │    │    │    │    │
 │    │    │    │    │
 │    │    │    │    └───── day of week (0 - 6 or mon, tue, wed, thu, fri, sat, sun)
 │    │    │    └────────── month (1 - 12)
 │    │    └─────────────── day of month (1 - 31)
 │    └──────────────────── hour (0 - 23)
 └───────────────────────── minute (0 - 59)
 
 Note: 'day of week' starts on monday. 
            </pre>
            </div>
       </fieldset>
    
       <fieldset>
            <legend>Job details</legend>
            <div>
                <label for="id_job_name" class="label">Job name: *</label>
                {{ jobForm.job_name }}
                {{ jobForm.job_name.errors }}
            </div>
            <div>
                <span class="label">Others may view and edit <br> my job *</span>
                {{ jobForm.is_public }}
                {{ jobForm.is_public.errors }}
            </div>
       </fieldset>
       <span class="floatright">* required</span><br>
       <input type="button" class="gradient" id="btn_save" value="Save">
       
       {% if jobForm.job_name.value %}
       <input type="hidden" id="id_edit_processed_jobs" name="edit_processed_jobs" value="">
       <input type="hidden" id="id_is_public_org" name="is_public_org" value="{{ jobForm.is_public.value }}">
       {{ jobForm.edit_processed_jobs.errors }}
       {{ jobForm.is_public_org.errors }}
       
       {% endif %}
    </form>
</div>
{% endif %}

{% block extrahead %}
    <script type="text/javascript" src="/static/js/apprise-1.5.min.js"></script>
    <script type="text/javascript" src="/static/js/use_ajax.js"></script>
    <script type="text/javascript" src="/static/js/job_form.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/apprise.min.css">
{% endblock %}

web/templates/jobs_overview.html
{% extends "base.html" %}
{% load ifjobrights %}

{% block extrahead %}
<!--  <script type="text/javascript" src="/site_media/js/job_overview.js"></script>-->
{% endblock %}

{% block title %}Jobs Overview{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">Jobs Overview</div>
{% endblock %}

{% block content %}
<div class="dataTables_filter" id="jobSearchWrapper">
	<form method="post" action="." id="job_search_form">{% csrf_token %}
		<label for="jobSearchJobName">Search by job name: </label>
		{{ jobSearchForm.job_search }}
		<input type="submit" class="gradient" id="btn_search" value="Search">
	</form>
</div>
<table class="tbl_overview">
    <thead>
        <tr class="topdowngradient">
            <th>Job Name</th>
            <th>Submitted</th>
            <th>Finished</th>
            <th>Current scheduling</th>
            <th>Feeds</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
{% for job in jobs.object_list %}
    {% ifjobrights job user %}
        <tr>
            <td ><a href="/job/{{ job.id }}">{{ job.name }}</a></td>
            <td class="nowrap">{{ job.started|date:"N d, Y, H:i" }}</td>
            <td class="nowrap">{{ job.finished|date:"N d, Y, H:i" }}</td>
            <td class="nowrap">
                <a href="/schedule/{{ job.schedule.id }}/">
	            {% if job.schedule.scheduled_start %}
		            Once at {{ job.schedule.scheduled_start|date:"H:i" }}
	            {% else %}
					{{ job.schedule.cron_expression }}
	            {% endif %}                
                </a>
            </td>            
            <td class="nowrap">
                <a href="/feeds/{{ job.schedule.id }}/all/">All</a> | 
                <a href="/feeds/{{ job.schedule.id }}/nonbenign/">Non-Benign</a>
            </td>
            <td><span class="{{ job.get_status_display|lower }} bold">{{ job.get_status_display|upper }}</span></td>
        </tr>
        
        {% endifjobrights %}
         
{% endfor %}    
    
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">

        {% if jobs.has_previous %}
            <a href="?page={{ jobs.previous_page_number }}"><img src="/static/img/left_24.png"></a>
        {% else %}
        <img src="/static/img/left_24.png" class="img_disabled">
        {% endif %}

        <span class="current">
            {{ jobs.start_index }} - {{ jobs.end_index }} of {{ jobs.paginator.count }}
        </span>

        {% if jobs.has_next %}
            <a href="?page={{ jobs.next_page_number }}"><img src="/static/img/right_24.png"></a>
        {% else %}
        <img src="/static/img/right_24.png" class="img_disabled">
        {% endif %}            

    </span>
</div>

{% endblock %}

web/templates/new_job.html
{% extends "base.html" %}

{% block title %}Create new job{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">Create New Job</div>
{% endblock %}

{% block content %}

{% include "job_form.html" %}

{% endblock %}